"""empty message

Revision ID: 2ddc3047c753
Revises: c12c91b9c6b4
Create Date: 2023-03-17 08:13:09.976952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ddc3047c753'
down_revision = 'c12c91b9c6b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.Float(), nullable=False))
        batch_op.drop_column('sscore')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sscore', sa.FLOAT(), nullable=False))
        batch_op.drop_column('score')

    # ### end Alembic commands ###
