"""empty message

Revision ID: 45ee8eb3795a
Revises: 2ddc3047c753
Create Date: 2023-03-17 13:55:36.597328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45ee8eb3795a'
down_revision = '2ddc3047c753'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('course_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('form_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'courses', ['course_id'], ['id'])
        batch_op.create_foreign_key(None, 'forms', ['form_id'], ['id'])
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'forms', ['id'], ['id'])
        batch_op.drop_column('form_id')
        batch_op.drop_column('course_id')
        batch_op.drop_column('student_id')

    # ### end Alembic commands ###
