"""empty message

Revision ID: 5165e0879881
Revises: 
Create Date: 2023-03-16 11:55:05.995353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5165e0879881'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forms', schema=None) as batch_op:
        batch_op.alter_column('grades',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forms', schema=None) as batch_op:
        batch_op.alter_column('grades',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###
