"""empty message

Revision ID: 7d6a2158d18a
Revises: a54100139bc4
Create Date: 2023-03-19 18:20:38.015870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d6a2158d18a'
down_revision = 'a54100139bc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('form_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('form_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'forms', ['form_id'], ['id'])

    # ### end Alembic commands ###
