"""empty message

Revision ID: c12c91b9c6b4
Revises: e1e028912884
Create Date: 2023-03-17 08:01:29.334334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c12c91b9c6b4'
down_revision = 'e1e028912884'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sscore', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['forms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('forms', schema=None) as batch_op:
        batch_op.drop_column('grades')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grades', sa.FLOAT(), nullable=True))

    op.drop_table('scores')
    # ### end Alembic commands ###
